wip: try to find cppcheck

diff --git a/.github/workflows/static-analysis.yml b/.github/workflows/static-analysis.yml
--- a/.github/workflows/static-analysis.yml
+++ b/.github/workflows/static-analysis.yml
@@ -23,6 +23,21 @@ jobs:
           echo "C:\Program Files\LLVM\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
           echo "C:\ProgramData\chocolatey\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
 
+      - name: Find cppcheck
+        run: |
+          Get-Command cppcheck.exe
+          if (!(Get-Command cppcheck.exe -ErrorAction SilentlyContinue)) {
+            Write-Host "cppcheck not in PATH, searching..."
+            $cppcheckPath = Get-ChildItem -Path 'C:\ProgramData\chocolatey\' -Filter cppcheck.exe -Recurse -ErrorAction SilentlyContinue | Select-Object -First 1 -ExpandProperty FullName
+            if ($cppcheckPath) {
+              Write-Host "Found cppcheck at $cppcheckPath"
+              echo "$(Split-Path $cppcheckPath)" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
+            } else {
+              Write-Error "cppcheck.exe not found!"
+              exit 1
+            }
+          }
+
       - name: Configure CMake
         run: cmake -B build -G Ninja -DCMAKE_C_COMPILER=clang -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
 
